version: '3.8'

services:

  beanba-server-blue:
    build:
      context: ./server-docker
      dockerfile: Dockerfile
    container_name: beanba-blue
    ports:
      - "8083:8080"
    env_file:
      - ../backendProject/beanBa/.env
    volumes:
      - ./app.jar:/app.jar
    networks:
      - prod_server

networks:
  prod_server:
    external: true
